/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cart_mart_2;

import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;

/**
 *
 * @author david
 */
public class ReceiptView extends javax.swing.JFrame {

    private ItemList inventory;
    private ItemList order;
    public int orderNumber = 0;
    public static int orderTotal = 0;

    /**
     * Creates new form ReceiptView. Overloaded constructor is to display order
     * history as an order number is not needed
     *
     * @param list
     */
    public ReceiptView(ItemList list) {
        LocalDateTime time = LocalDateTime.now();
        DateTimeFormatter formatTime = DateTimeFormatter.ofPattern("MMddyyHHmm");
        String formattedDate = time.format(formatTime);
        orderNumber = Integer.valueOf(formattedDate);
        Order.orderNumber = orderNumber;
        ImageIcon logo = new ImageIcon(Cart_Mart_2.class.getResource("images/cartLogo.png"));
        this.setIconImage(logo.getImage());
        this.setTitle("Cart Mart");
        this.inventory = list;
        initComponents();
        ViewItems itemPanel = new ViewItems();
        itemPanel.viewItemResults(list);
        Cart_Mart_2.printOrder();
        this.revalidate();
        totalLabel.setText("Total: $" + String.format("%.2f", (float) orderTotal / 100.0));
        viewPanel.setBackground(Color.GREEN);
        viewPanel.setViewportView(itemPanel);
        viewPanel.setVisible(true);
        itemPanel.setVisible(true);
    }

    public ReceiptView() {
        this.inventory = Item.inventory;
        order = new ItemList();
        for (int i = 0; i < Order.itemIdList.size(); i++) {
            for (int j = 0; j < inventory.getCount(); j++) {
                if (Order.itemIdList.get(i) == inventory.getItem(j).getItemId()) {
                    order.addItem(inventory.getItem(j));
                }
            }
        }
        for (int i = 0; i < order.getCount() - 1; i++) {
            for (int j = i + 1; j < order.getCount(); j++) {
                if (order.getItem(i).getItemId() == order.getItem(j).getItemId()) {
                    order.removeItem(i);
                    Order.itemIdList.remove(i);
                    Order.qtyList.remove(i);
                }
            }
        }
        ImageIcon logo = new ImageIcon(Cart_Mart_2.class.getResource("images/cartLogo.png"));
        this.setIconImage(logo.getImage());
        this.setTitle("Cart Mart");
        initComponents();

        ViewItems itemPanel = new ViewItems();
        itemPanel.viewItemResults(order);
        viewPanel.setBackground(Color.GREEN);
        viewPanel.setViewportView(itemPanel);
        viewPanel.setVisible(true);
        itemPanel.setVisible(true);
    }

    public void turnOn() {
        this.getContentPane().setBackground(Color.black);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        welcomLabel = new javax.swing.JLabel();
        accountButton1 = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        orderLabel = new javax.swing.JLabel();
        viewPanel = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        navPanel.setBackground(new java.awt.Color(255, 255, 255));
        navPanel.setLayout(null);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cart_mart_2/images/cartLogo100.png"))); // NOI18N
        logoLabel.setText("jLabel1");
        logoLabel.setMaximumSize(new java.awt.Dimension(100, 100));
        logoLabel.setMinimumSize(new java.awt.Dimension(100, 100));
        logoLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        navPanel.add(logoLabel);
        logoLabel.setBounds(0, 0, 100, 100);

        welcomLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        welcomLabel.setText("Thank you for your purchase " + User.receiptName);
        navPanel.add(welcomLabel);
        welcomLabel.setBounds(110, 0, 540, 33);

        accountButton1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        accountButton1.setLabel("Account");
        accountButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountButton1ActionPerformed(evt);
            }
        });
        navPanel.add(accountButton1);
        accountButton1.setBounds(110, 30, 100, 27);

        totalLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        totalLabel.setText("Total: "+String.valueOf(orderTotal));
        navPanel.add(totalLabel);
        totalLabel.setBounds(300, 70, 130, 30);

        orderLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        orderLabel.setText("Order#: "+String.valueOf(orderNumber));
        navPanel.add(orderLabel);
        orderLabel.setBounds(110, 70, 180, 30);

        viewPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
            .addComponent(viewPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountButton1ActionPerformed
        // TODO add your handling code here:
        Cart_Mart_2.changeView(9, 3);
    }//GEN-LAST:event_accountButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceiptView().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountButton1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel navPanel;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JScrollPane viewPanel;
    private javax.swing.JLabel welcomLabel;
    // End of variables declaration//GEN-END:variables
}
