/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cart_mart_2;

import javax.swing.ImageIcon;

/**
 *
 * @author Krina
 */
public class WelcomePage extends javax.swing.JFrame {

    /**
     * Creates new form WelcomePage
     */
    public WelcomePage() {
        ImageIcon logo = new ImageIcon(Cart_Mart_2.class.getResource("images/cartLogo.png"));
        this.setIconImage(logo.getImage());
        this.setTitle("Cart Mart");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        cartCountLabel = new javax.swing.JLabel();
        emptyCartLabel = new javax.swing.JLabel();
        welcomLabel = new javax.swing.JLabel();
        sortLabel = new javax.swing.JLabel();
        searchLabel = new javax.swing.JLabel();
        sortMenu = new javax.swing.JComboBox<>();
        searchBar = new javax.swing.JTextField();
        goButton = new javax.swing.JButton();
        accountButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        PickUp = new javax.swing.JButton();
        Delivery1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        navPanel1 = new javax.swing.JPanel();
        logoLabel1 = new javax.swing.JLabel();
        welcomLabel1 = new javax.swing.JLabel();
        accountButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        navPanel.setBackground(new java.awt.Color(255, 255, 255));
        navPanel.setLayout(null);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cart_mart_2/images/cartLogo100.png"))); // NOI18N
        logoLabel.setText("jLabel1");
        logoLabel.setMaximumSize(new java.awt.Dimension(100, 100));
        logoLabel.setMinimumSize(new java.awt.Dimension(100, 100));
        logoLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        navPanel.add(logoLabel);
        logoLabel.setBounds(0, 0, 100, 100);

        cartCountLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 36)); // NOI18N
        cartCountLabel.setForeground(new java.awt.Color(255, 0, 0));
        cartCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartCountLabel.setText("0");
        cartCountLabel.setMaximumSize(new java.awt.Dimension(65, 65));
        cartCountLabel.setMinimumSize(new java.awt.Dimension(65, 65));
        cartCountLabel.setPreferredSize(new java.awt.Dimension(65, 65));
        navPanel.add(cartCountLabel);
        cartCountLabel.setBounds(615, 15, 80, 70);

        emptyCartLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cart_mart_2/images/emptyCart100.png"))); // NOI18N
        emptyCartLabel.setMaximumSize(new java.awt.Dimension(100, 100));
        emptyCartLabel.setMinimumSize(new java.awt.Dimension(100, 100));
        emptyCartLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        navPanel.add(emptyCartLabel);
        emptyCartLabel.setBounds(600, 0, 100, 100);

        welcomLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        welcomLabel.setText("Welcome to Cart Mart!");
        navPanel.add(welcomLabel);
        welcomLabel.setBounds(110, 0, 280, 33);

        sortLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        sortLabel.setText("Sort:");
        navPanel.add(sortLabel);
        sortLabel.setBounds(330, 70, 50, 21);

        searchLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 18)); // NOI18N
        searchLabel.setText("Search:");
        navPanel.add(searchLabel);
        searchLabel.setBounds(110, 70, 80, 21);

        sortMenu.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        sortMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Price low to high", "Price high to low", "Name A-Z", "Name Z-A", "Department:", "     Bakery", "     Dry Grocery", "     Frozen", "     Meat", "     Produce", "     Refrigerated" }));
        sortMenu.setLightWeightPopupEnabled(false);
        sortMenu.setMaximumSize(new java.awt.Dimension(136, 27));
        sortMenu.setMinimumSize(new java.awt.Dimension(136, 27));
        sortMenu.setPreferredSize(new java.awt.Dimension(136, 27));
        navPanel.add(sortMenu);
        sortMenu.setBounds(380, 70, 136, 27);

        searchBar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        searchBar.setMaximumSize(new java.awt.Dimension(136, 27));
        searchBar.setMinimumSize(new java.awt.Dimension(136, 27));
        searchBar.setPreferredSize(new java.awt.Dimension(136, 27));
        navPanel.add(searchBar);
        searchBar.setBounds(180, 70, 136, 27);

        goButton.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        goButton.setText("GO!");
        navPanel.add(goButton);
        goButton.setBounds(520, 70, 70, 29);

        accountButton.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        accountButton.setLabel("Account");
        navPanel.add(accountButton);
        accountButton.setBounds(110, 30, 100, 29);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 48)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PickUp.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 36)); // NOI18N
        PickUp.setText("Pick Up");
        PickUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PickUpActionPerformed(evt);
            }
        });

        Delivery1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 36)); // NOI18N
        Delivery1.setText("Delivery");
        Delivery1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delivery1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 51, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        navPanel1.setBackground(new java.awt.Color(255, 255, 255));
        navPanel1.setLayout(null);

        logoLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cart_mart_2/images/cartLogo100.png"))); // NOI18N
        logoLabel1.setText("jLabel1");
        logoLabel1.setMaximumSize(new java.awt.Dimension(100, 100));
        logoLabel1.setMinimumSize(new java.awt.Dimension(100, 100));
        logoLabel1.setPreferredSize(new java.awt.Dimension(100, 100));
        navPanel1.add(logoLabel1);
        logoLabel1.setBounds(0, 0, 100, 100);

        welcomLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        welcomLabel1.setText("Welcome to Cart Mart!");
        navPanel1.add(welcomLabel1);
        welcomLabel1.setBounds(110, 0, 300, 33);

        accountButton1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        accountButton1.setText("Login Page");
        accountButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountButton1ActionPerformed(evt);
            }
        });
        navPanel1.add(accountButton1);
        accountButton1.setBounds(110, 30, 140, 29);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 48)); // NOI18N
        jLabel1.setText("Select Order Method");
        navPanel1.add(jLabel1);
        jLabel1.setBounds(370, 40, 464, 55);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(PickUp)
                .addGap(166, 166, 166)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(Delivery1)
                .addGap(223, 223, 223))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 209, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Delivery1)
                                .addGap(211, 211, 211))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(PickUp)
                                .addGap(209, 209, 209))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PickUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PickUpActionPerformed
        // TODO add your handling code here:
        Cart_Mart_2.changeView(7, 6);
    }//GEN-LAST:event_PickUpActionPerformed

    private void Delivery1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delivery1ActionPerformed
        // TODO add your handling code here:
        Cart_Mart_2.changeView(8, 6);
    }//GEN-LAST:event_Delivery1ActionPerformed

    private void accountButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountButton1ActionPerformed
        // TODO add your handling code here:
        Cart_Mart_2.changeView(5, 6);
    }//GEN-LAST:event_accountButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delivery1;
    private javax.swing.JButton PickUp;
    private javax.swing.JButton accountButton;
    private javax.swing.JButton accountButton1;
    private javax.swing.JLabel cartCountLabel;
    private javax.swing.JLabel emptyCartLabel;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel logoLabel1;
    private javax.swing.JPanel navPanel;
    private javax.swing.JPanel navPanel1;
    private javax.swing.JTextField searchBar;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel sortLabel;
    private javax.swing.JComboBox<String> sortMenu;
    private javax.swing.JLabel welcomLabel;
    private javax.swing.JLabel welcomLabel1;
    // End of variables declaration//GEN-END:variables
}
